services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ragtoolkit
      POSTGRES_USER: ragtoolkit
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-please_change_this_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ragtoolkit"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://ragtoolkit:${POSTGRES_PASSWORD:-please_change_this_password}@postgres:5432/ragtoolkit
      RAGTOOLKIT_API_KEY: ${RAGTOOLKIT_API_KEY:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn ragtoolkit.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    working_dir: /app

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data: 