services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ragtoolkit
      POSTGRES_USER: ragtoolkit
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ragtoolkit"]
      interval: 5s
      timeout: 5s
      retries: 5

  ragtoolkit:
    image: ragtoolkit/ragtoolkit:latest
    environment:
      DATABASE_URL: postgresql://ragtoolkit:test_password@postgres:5432/ragtoolkit
      RAGTOOLKIT_API_KEY: test_key_123
    ports:
      - "8001:8000"  # API on port 8001 to avoid conflicts
      - "3001:3000"  # Frontend on port 3001
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
